### ISSUE TITLE
[FE] 프론트엔드 초기 환경 세팅

### ISSUE THREAD

**Issue by silvertae** [codesquad-members-2023/gaemi-marble-team-04#1]
## ✅ ToDo
- [x] vite 이용해서 React, TypeScript + SWC 기반 프로젝트 환경세팅
- [x] styled-components 설치
- [x] reset css 기본 설정
- [x] react-router 설치 및 적용
- [x] 테스트 페이지 구현
- [x] 디자인 시스템 구축

## 🖐️ P.S. 
- 우선 가장 익숙한 환경으로 작업하기 위해서 vite, styled-components로 기본 설정만 미리 해두었습니다
