### ISSUE TITLE
[FE] 로그인/회원가입 페이지 작업

### ISSUE THREAD

**Issue by silvertae** [codesquad-members-2023/gaemi-marble-team-04#12]
## ✅ ToDo
- [x] api 요청 함수 구현 (로그인/회원가입/로그아웃)
- [x] 로그인/회원가입 인풋 정규식
- [x] token 및 user 정보 상태관리 (with. Jotai)
  - [x] Jotai 기본 사용법 익히기 
- [x] ProtectedRoute 적용
