### ISSUE TITLE
[BE] API 및 웹소켓 기능 구현

### ISSUE THREAD

**Issue by HyowonSin** [codesquad-members-2023/gaemi-marble-team-04#21]
## ✅ ToDo
- [x] 게임 방 생성
- [x] 게임 방 유무 체크
- [x] 입장하기
- [x] 게임 준비 상태 변경
- [x] 게임 시작 요청
- [x] 주사위 굴리기
- [x] 이벤트 목록 선정

## 🖐️ P.S. 
- 설계 수정
