### ISSUE TITLE
[FE] 플레이어 말 이동 기능

### ISSUE THREAD

**Issue by silvertae** [codesquad-members-2023/gaemi-marble-team-04#25]
## ✅ ToDo
- [x] PlayerToken 컴포넌트 구현
- [x] 주사위눈 결과에 맞게 플레이어 말을 이동시키는 함수 구현
- [x] 관련 상태 추가

## 🖐️ P.S. 
-
