### ISSUE TITLE
[BE] CI/CD 구축

### ISSUE THREAD

**Issue by HyowonSin** [codesquad-members-2023/gaemi-marble-team-04#36]
## ✅ ToDo
- [x] be workflow 작성
- [ ] fe workflow 작성
- [x] spring boot 배포 확인
- [ ] nginx 배포 확인
- [x] rds 연결 확인

## 🖐️ P.S. 
- docker-compose

**Comment by HyowonSin** [comment]
fe ci/cd를 fe에서 해주셔서 리버스 프록시 용도였던 nginx 를 쓰지 않아도 되게 되었습니다.
짝짝~
