### ISSUE TITLE
[FE] 플레이어 게임준비 기능 및 룰렛 기능

### ISSUE THREAD

**Issue by silvertae** [codesquad-members-2023/gaemi-marble-team-04#42]
## ✅ ToDo
- [x] 플레이어별 게임준비 버튼
- [x] 준비 상태 변경 기능
- [x] 마지막 플레이어 턴 종료시 이벤트 룰렛 렌더링

## 🖐️ P.S. 
-
