### ISSUE TITLE
[BE] API 응답 수정, 누락 데이터 반영

### ISSUE THREAD

**Issue by HyowonSin** [codesquad-members-2023/gaemi-marble-team-04#43]
## ✅ ToDo
- [x] 이벤트 결정 요청 시, 랜덤 이벤트 선정하여 추가 메시지 전송  
&rarr; 즉, 6개 이벤트 중 랜덤하게 선택된 이벤트 결과와 전체 현황판 각각 Response
- [x] 전체 현황판 업데이트 시, 플레이어 보유 자산 반영 (GameStatus)
- [x] 개인 현황판 응답 시, 주식 수량 추가
- [x] 게임 입장 응답 시, 준비 상태 추가

## 🖐️ P.S. 
- 1번은 룰렛 눌렀을 때 모든 플레이어에게 같은 결과를 보여주기 위함
