### ISSUE TITLE
[BE] 오류 수정, 추가 응답 등

### ISSUE THREAD

**Issue by HyowonSin** [codesquad-members-2023/gaemi-marble-team-04#51]
## ✅ ToDo
- [x] 게임방 입장 중복 불가 처리
- [x] 게임방 입장 시 전체현황판 추가 응답
- [x] 게임 준비 상태 취소 안 되는 것 처리
- [x] 이벤트 이름 길이 조절  
`성공적인 맥도날드, 농심 콜라보` &rarr;  `맥도날드x농심 콜라보!`

## 🖐️ P.S. 
-
