### ISSUE TITLE
[FE] 감옥칸 기능 구현 & 토큰 이동관련 상태 개선하기

### ISSUE THREAD

**Issue by silvertae** [codesquad-members-2023/gaemi-marble-team-04#54]
## ✅ ToDo
- [x] 보드게임판 각 기업칸 가격 표시
- [x] 다음 라운드 시작전 룰렛으로 선정된 이벤트 결과 및 효과 모달로 표시
- [x] playerToken 스토어 상태 개선하기
- [x] 플레이어 턴 시작시 감옥일 때 다른 화면 렌더링
- [x] 감옥칸 기능 구현

## 🖐️ P.S. 
-
