### ISSUE TITLE
[FE] 프로토타입에서 발견된 버그들 수정

### ISSUE THREAD

**Issue by silvertae** [codesquad-members-2023/gaemi-marble-team-04#72]
## ✅ ToDo
- [x] 화면크기에 따라 깨지는 레이아웃 수정하기
- [x] 보드게임판 칸 헤더 높이 들쭉날쭉한 부분 수정
- [x] 매도하기 창 버튼 수정
- [x] 이벤트 룰렛 돌리는 방식 수정
