### ISSUE TITLE
[FE] 프로토타입 남은 버그들 수정

### ISSUE THREAD

**Issue by silvertae** [codesquad-members-2023/gaemi-marble-team-04#77]
## ✅ ToDo
- [ ] 플레이어가 꽉 찬 게임방 입장시 웹소켓으로 오는 error 타입 메세지 처리 -> 게임페이지에서 홈으로 나가서 웹소켓 연결을 끊도록
- [ ] 감옥, 호재칸, 세금칸 등 특수칸 도착시 안내문구 출력 기능 추가
- [ ] 굴리기 -> 턴종료 연속클릭시 버그 수정
